name: dashboard-conda-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - ipykernel
  - ipython
  - jupyterlab
  - jupyterlab-server
  - jupyter-server
  - jupyterhub
  - matplotlib
  - pyyaml
  - scipy
  - scikit-learn
  - grpcio
  - protobuf
  - sqlalchemy
  - alembic
  - tornado
  - tqdm
  - cffi
  - cryptography
  - psutil
  - brotli
  - zstandard
  - pip:
      # all other pip-only packages go here:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - alembic==1.15.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - arrow==1.3.0
      - asgiref==3.8.1
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certipy==0.2.2
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - click==8.1.8
      - coloredlogs==15.0.1
      - comm==0.2.2
      - conda  # installed via Conda, skip in pip
      - deprecated==1.2.18
      - durationpy==0.9
      - executing==2.2.0
      - fastapi==0.115.12
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - google-auth==2.40.1
      - googleapis-common-protos==1.70.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.31.2
      - humanfriendly==10.0
      - idna==...
      # and so on
