[project]
name = "dashboard-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "pydeck>=0.9.1",
    "streamlit>=1.45.1",
]
